# Site settings
title: "A ATM 623: Climate Modeling"
email: brose@albany.edu
description: > # this means to ignore newlines until "baseurl:"
  Class website for A ATM 623, Spring 2019
baseurl: "/facstaff/brose/classes/ATM623_Spring2019" # the subpath of your site, e.g. /blog
url: "http://www.atmos.albany.edu/facstaff/brose/classes/ATM623_Spring2019" # the base hostname & protocol for your site
twitter_username: BrianEJRose
github_username: brian-rose

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
